# Generated by Django 2.1.5 on 2019-02-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190220_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastlogin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
